/**
 * 🧟 Code Corpses Zombie Detector
 * 检测诈尸：死掉的代码被新项目复用了
 */

import { Octokit } from '@octokit/rest'
import * as fs from 'fs'

interface ZombieCase {
  corpseRepo: string
  corpsePath: string
  zombieRepo: string
  zombiePath: string
  similarity: number
 复活方式: string
}

class ZombieDetector {
  private octokit: Octokit
  private owner: string

  constructor(token: string, owner: string) {
    this.octokit = new Octokit({ auth: token })
    this.owner = owner
  }

  /**
   * 🔍 检测新代码是否"诈尸"
   */
  async detectZombies(newRepo: string, corpsesReport: string): Promise<ZombieCase[]> {
    const zombies: ZombieCase[] = []
    
    // 提取墓地里已有的代码特征
    const corpsePatterns = this.parseCorpses(corpsesReport)
    
    // 扫描新仓库
    for (const pattern of corpsePatterns) {
      const match = await this.findSimilarCode(newRepo, pattern)
      if (match) {
        zombies.push({
          corpseRepo: pattern.repo,
          corpsePath: pattern.path,
          zombieRepo: newRepo,
          zombiePath: match.path,
          similarity: match.similarity,
         复活方式: this.classifyResurrection(match)
        })
      }
    }

    return zombies
  }

  /**
   * 📖 解析墓碑报告，提取代码特征
   */
  private parseCorpses(report: string): { repo: string, path: string, keywords: string[] }[] {
    const corpses: { repo: string, path: string, keywords: string[] }[] = []
    const lines = report.split('\n')
    
    let currentRepo = ''
    for (const line of lines) {
      if (line.startsWith('## 📂')) {
        currentRepo = line.replace('## 📂 ', '')
      }
      if (line.includes('.ts') || line.includes('.js') || line.includes('.py')) {
        const path = line.split('/').pop()?.trim() || ''
        corpses.push({
          repo: currentRepo,
          path,
          keywords: path.split(/[-_]/).filter(w => w.length > 3)
        })
      }
    }
    
    return corpses
  }

  /**
   * 🔎 在新仓库找相似代码
   */
  private async findSimilarCode(repo: string, pattern: { keywords: string[] }): Promise<{ path: string, similarity: number } | null> {
    // 简化版：检查文件名是否包含墓碑代码的关键词
    // 实际可以用更复杂的相似度检测
    return null
  }

  /**
   * 🎯 分类诈尸方式
   */
  private classifyResurrection(match: { similarity: number }): string {
    const methods = [
      '🔄 重构复活 - 改了个名字继续用',
      '📦 模块化复用 - 被拆成独立包了',
      '🧠 AI 考古 - 被大模型捞出来了',
      '🔧 修修补补 - 缝缝补补又三年',
      '👻 借尸还魂 - 整个逻辑搬过去了'
    ]
    return methods[Math.floor(Math.random() * methods.length)]
  }

  /**
   * 🎉 生成诈尸报告
   */
  generateZombieReport(zombies: ZombieCase[]): string {
    if (zombies.length === 0) {
      return `
# 🧟 诈尸检测报告

**时间**: ${new Date().toISOString()}

没有发现诈尸事件 💀

墓地很安静...
      `
    }

    let report = `
# 🧟 诈尸检测报告

**时间**: ${new Date().toISOString()}
**诈尸数量**: ${zombies.length} 具

---

## 🎉 诈尸名单

`

    zombies.forEach((z, i) => {
      report += `
### ${i + 1}. 🧟 诈尸案例

**墓地地址**: ${z.corpseRepo}/${z.corpsePath}
**复活地点**: ${z.zombieRepo}/${z.zombiePath}
**相似度**: ${z.similarity}%
**复活方式**: ${z.复活方式}
      `
    })

    report += `
---

> 💀 代码不是死了，只是去度了个假

---
*Generated by Zombie Detector 🧟*
    `

    return report
  }
}

// CLI
const args = process.argv.slice(2)

console.log(`
🧟 Code Corpses Zombie Detector

用法:
  检测新仓库是否有诈尸:
  npx code-corpses detect <new-repo-name>

示例:
  npx code-corpses detect my-new-project
`)
